spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow_demo?characterEncoding=utf8&useSSL=false
    username: root
    password: wangtao
    driver-class-name: com.mysql.cj.jdbc.Driver

camunda:
  bpm:
    database:
      type: mysql
      schema-update: true # 是否自动建表，但我测试为true时，创建表会出现，因此还是改成false由手工建表。
    auto-deployment-enabled: true # 自动部署 resources 下的 bpmn文件
    admin-user:
      id: admin
      password: 123456
  flyway:
    enabled: true
    locations: classpath:db/migration/camunda
